version: '3'

services:
  my-nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      # `--no-cache` Option beim Build
      args:
        - NO_CACHE=true
    ports:
      - "3001:3000"
    container_name: my-nestjs-app
    restart: unless-stopped
